version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip3 install virtualenv
      - virtualenv ml-service
      - source ml-service/bin/activate
      - pip3 install -r requirements.txt
  build:
    commands:
      - pip3 install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html